import sys

import pygame

from settings import Settings
from ship import Ship

class AlienInvasion:
    """General class dedicated to the managing the resources and the 
    way the game works.
    """

    def __init__(self):
        """The game initialization and the setting up its resources."""
        pygame.init()
        self.settings = Settings()

        self.screen = pygame.display.set_mode((self.settings.screen_width, \
            self.settings.screen_height))
        pygame.display.set_caption("Alien Invasion")

        self.ship = Ship(self)

    def run_game(self):
        """Start of the main loop of the game"""
        while True:
            self._check_events()
            self._update_screen()

    def _check_events(self):
        """Reaction for the events generated by the keyboard and 
        the mouse.
        """
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_d or event.key == pygame.K_RIGHT:
                    # Moving of the spaceship to the right.
                    self.ship.rect.x += 1

    def _update_screen(self):
        """Updating of the view on the screen and the transition to 
        the new screen.
        """
        self.screen.fill(self.settings.bg_color)
        self.ship.blitme()

        pygame.display.flip()

if __name__ == '__main__':
    # Setting up of the object of the game and the start-up of 
    # the game.
    ai = AlienInvasion()
    ai.run_game()